'use client';

import { useState } from 'react';
import { Bell, Camera, ChevronRight, Heart, ImagePlus, Menu, Search, ShoppingBag, Sparkles, User, X, ArrowUpRight, SlidersHorizontal } from 'lucide-react';

type Product={id:number;name:string;category:string;price:number;image:string;reason:string;tag?:string};
const products:Product[]=[
{id:1,name:'Structured Overshirt',category:'Men · Fashion',price:3290,image:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=85',reason:'Matches your minimal style',tag:'AI PICK'},
{id:2,name:'Cloud Runner',category:'Running · Shoes',price:5490,image:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85',reason:'Because you like lightweight shoes'},
{id:3,name:'Noise Cancelling Headphones',category:'Audio · Tech',price:8990,image:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=85',reason:'Based on your tech history'},
{id:4,name:'Minimal Steel Watch',category:'Accessories',price:6990,image:'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=900&q=85',reason:'Fits your preferred colours'},
{id:5,name:'Everyday Knit Polo',category:'Men · Fashion',price:2490,image:'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=900&q=85',reason:'Popular with similar shoppers'},
{id:6,name:'Workspace Lamp',category:'Home · Living',price:3790,image:'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=85',reason:'You recently explored home upgrades'}
];
const interests=['Men’s Fashion','Sneakers','Technology','Home & Living','Fitness'];
const collections=[
['Minimal wardrobe','Pieces that work with what you already like','https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=900&q=85'],
['Better everyday tech','Useful upgrades, selected around your interests','https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=85'],
['Move more','Running and fitness picks for your routine','https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=900&q=85']
];

export default function Home(){
 const [loggedIn,setLoggedIn]=useState(false),[login,setLogin]=useState(false),[upload,setUpload]=useState(false),[liked,setLiked]=useState<number[]>([]),[query,setQuery]=useState(''),[tryProduct,setTryProduct]=useState<Product|null>(null),[tryHistory,setTryHistory]=useState<Product[]>([]);
 const toggleLike=(id:number)=>setLiked(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 const requestUpload=()=>loggedIn?setUpload(true):setLogin(true);
 const openTryOn=(product:Product)=>{if(!loggedIn){setLogin(true);return;}setTryProduct(product);setTryHistory(h=>[product,...h.filter(x=>x.id!==product.id)].slice(0,6));};
 const visible=products.filter(p=>`${p.name} ${p.category}`.toLowerCase().includes(query.toLowerCase()));
 return <main>
 <header className="topbar"><button className="menu"><Menu size={20}/></button><div className="brand"><span className="brand-mark"><Sparkles size={15}/></span>PERSONALIZED<span>ECOMMERCE</span></div><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your world"/></div><div className="actions"><button className="icon"><Bell size={18}/></button><button className="icon"><Heart size={18}/>{liked.length>0&&<i>{liked.length}</i>}</button><button className="icon"><ShoppingBag size={18}/></button>{loggedIn?<button className="avatar" onClick={()=>setLogin(true)}>S</button>:<button className="login-link" onClick={()=>setLogin(true)}>LOGIN</button>}</div></header>
 <section className="welcome"><div><p className="eyebrow"><Sparkles size={13}/> YOUR PERSONAL SHOPPING SPACE</p><h1><span className="hero-greeting">Hey John,</span><span className="hero-shopping">SHOPPING</span><span className="hero-personal"><span>made</span><span className="hero-personal-accent">personal.</span></span></h1><p>{loggedIn?"Your store is changing in real time based on what you like, explore and save.":'Explore freely. Sign in when you want us to start building a store around your taste.'}</p><div className="hero-actions"><button className="primary" onClick={()=>document.getElementById('foryou')?.scrollIntoView({behavior:'smooth'})}>Explore for you <ChevronRight size={16}/></button><button className="ghost" onClick={requestUpload}><Camera size={16}/> Try on with AI</button></div></div><div className="profile-card"><div className="profile-copy"><div className="profile-orb">✦</div><div><small>YOUR AI PROFILE</small><h3>{loggedIn?'Learning your taste':'Ready when you are'}</h3><p>{loggedIn?'Minimal · Modern · Tech · Fitness':'Sign in to save preferences and personalize every listing.'}</p></div><button onClick={()=>setLogin(true)}>{loggedIn?'View profile':'Personalize me'} <ChevronRight size={14}/></button></div><div className="profile-shopping-art" aria-hidden="true"><div className="art-spark one">✦</div><div className="art-spark two">✦</div><div className="art-bag"></div><div className="art-clothes"></div><div className="art-sunglasses">◒</div></div></div></section>
 <section className="interest-strip"><div><span className="eyebrow">TUNED FOR YOU</span><h2>Your top interests</h2></div><div className="interest-list">{interests.map((x,i)=><button key={x} className={i===0?'interest active':'interest'}>{['◐','◒','◈','⌂','◉'][i]} {x}</button>)}</div></section>
 <section id="foryou" className="section"><div className="section-head"><div><p className="eyebrow"><Sparkles size={13}/> FOR YOU</p><h2>Picked for your taste.</h2><p>Not a generic catalog. These are ranked around your interests, browsing signals and preferences.</p></div><button className="view-all">View all <ChevronRight size={16}/></button></div><div className="product-grid">{visible.map(p=><article className="product" key={p.id}><div className="product-image"><img src={p.image} alt={p.name}/>{p.tag&&<span className="tag">{p.tag}</span>}<button className={liked.includes(p.id)?'heart liked':'heart'} onClick={()=>toggleLike(p.id)}><Heart size={17} fill={liked.includes(p.id)?'currentColor':'none'}/></button><button className="try-on" onClick={()=>openTryOn(p)}><Sparkles size={14}/> Try on</button></div><div className="product-meta"><div><span className="reason"><Sparkles size={11}/>{p.reason}</span><h3>{p.name}</h3><p>{p.category}</p></div><b>₹{p.price.toLocaleString('en-IN')}</b></div></article>)}</div></section>
 <section className="taste-section"><div className="taste-copy"><p className="eyebrow"><SlidersHorizontal size={13}/> YOUR TASTE PROFILE</p><h2>Your store is learning what <em>feels like you.</em></h2><p>Every view, save and search helps us rank products more intelligently. You stay in control of what shapes your recommendations.</p><div className="signals"><span>Style <b>Minimal</b></span><span>Budget <b>₹2k–₹10k</b></span><span>Colours <b>Dark & neutral</b></span></div><button className="ghost">Manage profile <ArrowUpRight size={15}/></button></div><div className="taste-score"><small>PERSONALIZATION</small><strong>84<span>%</span></strong><p>We have a strong read on your current interests.</p><div className="score-bar"><i/></div><small className="score-note">Updated from your latest activity</small></div></section>
 <section className="collections section"><div className="section-head"><div><p className="eyebrow">PERSONALIZED COLLECTIONS</p><h2>Made from your interests.</h2></div></div><div className="collection-grid">{collections.map(([title,text,img],i)=><article className={'collection c'+i} key={title}><img src={img} alt=""/><div><span>0{i+1}</span><h3>{title}</h3><p>{text}</p><button>Explore <ArrowUpRight size={15}/></button></div></article>)}</div></section>
 <section className="ai-banner"><div className="ai-icon"><ImagePlus size={26}/></div><div><p className="eyebrow">AI TRY-ON</p><h2>See products with you in the picture.</h2><p>Upload your photo and make your shopping profile even more personal.</p></div><button className="primary" onClick={requestUpload}>Upload your photo <ChevronRight size={16}/></button></section>
 <section className="activity-section"><div className="section-head"><div><p className="eyebrow">CONTINUE EXPLORING</p><h2>Your recent signals.</h2><p>A quick look at the things helping shape your next recommendations.</p></div></div><div className="activity-grid"><article><b>12</b><span>Products viewed</span><p>More minimalist fashion than anything else this week.</p></article><article><b>{liked.length || 3}</b><span>Items saved</span><p>Saved items are getting more weight in your next product ranking.</p></article><article><b>04</b><span>Categories explored</span><p>Fashion, tech and fitness are your strongest current interests.</p></article><article className="explore-card"><Sparkles size={21}/><h3>Open the feed</h3><p>See everything the AI has selected for you.</p><button>Explore <ArrowUpRight size={15}/></button></article></div></section>
 <section className="section compact"><div className="section-head"><div><p className="eyebrow">DISCOVER</p><h2>New directions for you.</h2></div></div><div className="discover"><article><span>01</span><h3>Within your budget</h3><p>Products around the price range you usually explore.</p></article><article><span>02</span><h3>Because you liked</h3><p>More from styles, brands and categories you interact with.</p></article><article><span>03</span><h3>Try something new</h3><p>A little outside your usual pattern — still relevant to you.</p></article></div></section>
 <footer><div className="footer-top"><div className="footer-brand"><div className="brand"><span className="brand-mark"><Sparkles size={15}/></span>PERSONALIZED</div><h2>A store that gets better at knowing you.</h2><p>Discover products around your interests, not just the products everyone else sees.</p><div className="footer-search"><input placeholder="Get occasional product updates"/><button><ArrowUpRight size={17}/></button></div></div><div className="footer-links"><div><h4>DISCOVER</h4><a>For you</a><a>Collections</a><a>Categories</a><a>AI Try-On</a></div><div><h4>ACCOUNT</h4><a>My profile</a><a>Saved items</a><a>Orders</a><a>Preferences</a></div><div><h4>HELP</h4><a>How it works</a><a>Privacy</a><a>Contact</a><a>Feedback</a></div></div></div><div className="footer-bottom"><span>© 2026 Personalized Ecommerce</span><span>Built around your taste, always in your control.</span><div><a>Instagram</a><a>LinkedIn</a></div></div></footer>
 {login&&<LoginModal onClose={()=>setLogin(false)} onLogin={()=>{setLoggedIn(true);setLogin(false);}}/>}{upload&&<UploadModal onClose={()=>setUpload(false)}/>} {tryProduct&&<TryOnStudio product={tryProduct} history={tryHistory} onSelect={setTryProduct} onClose={()=>setTryProduct(null)}/>}</main>
}
function LoginModal({onClose,onLogin}:{onClose:()=>void;onLogin:()=>void}){return <div className="backdrop" onMouseDown={onClose}><div className="login-modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={onClose}><X size={19}/></button><div className="login-symbol"><Sparkles size={24}/></div><p className="eyebrow">WELCOME IN</p><h2>Make this store yours.</h2><p>Sign in to save your interests, history, likes and AI shopping profile.</p><button className="google" onClick={onLogin}>G <span>Continue with Google</span></button><div className="divider"><span>or</span></div><input placeholder="Email address" type="email"/><button className="primary wide" onClick={onLogin}>Continue <ChevronRight size={16}/></button><small>Demo login for this UI prototype.</small></div></div>}
function UploadModal({onClose}:{onClose:()=>void}){return <div className="backdrop" onMouseDown={onClose}><div className="upload-modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={onClose}><X size={19}/></button><div className="upload-drop"><ImagePlus size={34}/><h2>Your virtual model</h2><p>Drop a clear full-body photo here to begin your AI try-on experience.</p><button className="primary">Choose photo <ChevronRight size={16}/></button><small>JPG or PNG · Your image stays connected to your profile</small></div></div></div>}
function TryOnStudio({product,history,onSelect,onClose}:{product:Product;history:Product[];onSelect:(p:Product)=>void;onClose:()=>void}){return <div className="backdrop try-backdrop" onMouseDown={onClose}><div className="try-studio" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={onClose}><X size={19}/></button><div className="try-preview" style={{backgroundImage:`linear-gradient(90deg,rgba(19,20,24,.08),rgba(19,20,24,.2)),url(${product.image})`}}><div className="try-model"><div className="model-head"></div><div className="model-body"></div></div><span className="preview-label"><Sparkles size={13}/> Preview · {product.name}</span></div><div className="try-panel"><p className="eyebrow">TRY-ON STUDIO</p><h2>Your look, reimagined.</h2><div className="try-product"><img src={product.image} alt={product.name}/><div><h3>{product.name}</h3><p>{product.category} · ₹{product.price.toLocaleString('en-IN')}</p></div></div><div className="try-history-head"><span>Recently tried</span><b>{history.findIndex(x=>x.id===product.id)+1 || 1}/{history.length}</b></div><div className="try-history">{history.map(item=><button key={item.id} className={item.id===product.id?'active':''} onClick={()=>onSelect(item)}><img src={item.image} alt={item.name}/><span>{item.name}</span></button>)}</div><div className="try-actions"><button className="motion">See in motion <Sparkles size={14}/></button><button className="add-bag">Add to bag <ShoppingBag size={14}/></button></div><small>Try-on preview · Compare your recent looks before choosing.</small></div></div></div>}