'use client';
import { useState } from 'react';
import { ArrowRight, Heart, ImagePlus, Search, ShoppingBag, Sparkles, X } from 'lucide-react';

type Product={id:number;name:string;color:string;price:number;image:string;description:string};
const products:Product[]=[
{id:1,name:'Silk Column Dress',color:'Midnight',price:2890,image:'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?auto=format&fit=crop&w=900&q=85',description:'Fluid silk with a softly sculpted waist and a clean modern finish.'},
{id:2,name:'Satin Slip Dress',color:'Champagne',price:2490,image:'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=900&q=85',description:'Liquid satin, delicate straps and an effortless evening drape.'},
{id:3,name:'Tailored Midi',color:'Berry',price:3190,image:'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=900&q=85',description:'A precise midi cut with elegant structure and a confident line.'},
{id:4,name:'Linen Wrap Dress',color:'Olive',price:2190,image:'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=85',description:'Relaxed linen with a wrap waist and natural movement.'},
{id:5,name:'Asymmetric Pleat Dress',color:'Ink',price:3490,image:'https://images.unsplash.com/photo-1581044777550-4cfa60707c03?auto=format&fit=crop&w=900&q=85',description:'Architectural pleats and an asymmetric hem for a sharper statement.'},
{id:6,name:'Soft Knit Maxi',color:'Sand',price:2790,image:'https://images.unsplash.com/photo-1612336307429-8a898d10e223?auto=format&fit=crop&w=900&q=85',description:'Soft-touch knit with a minimal shape and effortless movement.'}
];

export default function Home(){const[selected,setSelected]=useState<Product|null>(null);const[tried,setTried]=useState<Product[]>([]);const[photo,setPhoto]=useState(false);const[detail,setDetail]=useState<Product|null>(null);
const open=(p:Product)=>{setSelected(p);setTried(v=>[p,...v.filter(x=>x.id!==p.id)].slice(0,5));};
return <main><header className="topbar"><div className="brand"><span className="brand-mark">S</span>SELENE</div><nav><button>New In</button><button>Dresses</button><button>Collections</button><button>Journal</button></nav><div className="actions"><button className="icon"><Search size={18}/></button><button className="icon"><Heart size={18}/></button><button className="icon"><ShoppingBag size={18}/><i>2</i></button></div></header>
<section className="hero"><div className="hero-copy"><p className="eyebrow"><Sparkles size={13}/> VIRTUAL TRY-ON STUDIO</p><h1>See it.<br/><em>Wear it.</em><br/>Make it yours.</h1><p className="hero-text">Explore the new season, then step into any look with our virtual fitting room.</p><button className="primary" onClick={()=>open(products[0])}>Try a look <ArrowRight size={16}/></button></div><div className="hero-image"><img src={products[2].image} alt="Fashion editorial"/><span>NEW SEASON<br/><b>FW / 26</b></span></div></section>
<section className="catalog"><div className="section-head"><div><p className="eyebrow">THE EDIT</p><h2>Made for your next chapter.</h2></div><small>06 pieces</small></div><div className="filters"><button className="active">All</button><button>Dresses</button><button>Evening</button><button>Everyday</button></div><div className="grid">{products.map(p=><article className="card" key={p.id}><div className="card-image"><img src={p.image} alt={p.name}/><button className="heart"><Heart size={17}/></button><button className="try" onClick={()=>open(p)}><Sparkles size={14}/> Try on</button></div><div className="meta"><div><strong>{p.name}</strong><span>{p.color} · Dresses</span></div><b>₹{p.price.toLocaleString('en-IN')}</b></div><button className="details" onClick={()=>setDetail(p)}>View details <ArrowRight size={13}/></button></article>)}</div></section>
{detail&&<Detail p={detail} close={()=>setDetail(null)} tryIt={()=>{setDetail(null);open(detail)}}/>}{selected&&<TryOn p={selected} tried={tried} photo={photo} setPhoto={setPhoto} select={open} close={()=>setSelected(null)}/>}</main>}

function TryOn({p,tried,photo,setPhoto,select,close}:{p:Product;tried:Product[];photo:boolean;setPhoto:(v:boolean)=>void;select:(p:Product)=>void;close:()=>void}){return <div className="backdrop" onMouseDown={close}><div className="studio" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close}><X size={19}/></button><div className="visual">{!photo?<div className="upload"><div className="upload-icon"><ImagePlus size={27}/></div><p className="eyebrow">YOUR VIRTUAL MODEL</p><h2>Let's see it on you.</h2><p>Upload a clear, full-body photo to preview the selected look.</p><button className="primary" onClick={()=>setPhoto(true)}>Upload photo <ArrowRight size={16}/></button><small>JPG or PNG · Full body works best</small></div>:<div className="preview"><img src={p.image} alt="Selected dress"/><div className="person"><div className="head"/><div className="body"/></div><span className="ai-note"><Sparkles size={13}/> Preview · {p.name}</span></div>}</div><aside><div className="studio-title"><div><p className="eyebrow">TRY-ON STUDIO</p><h3>{photo?'Your look, reimagined.':'Start with your photo.'}</h3></div><span className="ready">UI POC</span></div>{photo&&<div className="selected"><img src={p.image} alt=""/><div><b>{p.name}</b><span>{p.color} · ₹{p.price.toLocaleString('en-IN')}</span></div></div>}<div className="recent"><div className="recent-head"><span>Recently tried</span><span>{tried.length}/5</span></div><div className="thumbs">{tried.map(x=><button className={x.id===p.id?'thumb active':'thumb'} key={x.id} onClick={()=>select(x)}><img src={x.image} alt={x.name}/><span>{x.name}</span></button>)}</div></div>{photo&&<div className="studio-actions"><button className="secondary">See in motion <Sparkles size={14}/></button><button className="primary">Add to bag <ShoppingBag size={14}/></button></div>}<p className="fine">UI-only preview. AI generation will be connected later.</p></aside></div></div>}
function Detail({p,close,tryIt}:{p:Product;close:()=>void;tryIt:()=>void}){return <div className="backdrop"><div className="detail"><button className="close" onClick={close}><X size={19}/></button><div className="detail-img"><img src={p.image} alt={p.name}/><span>FW / 26</span></div><div className="detail-copy"><p className="eyebrow">SELENE · THE EDIT</p><h2>{p.name}</h2><strong className="price">₹{p.price.toLocaleString('en-IN')}</strong><p className="desc">{p.description}</p><label>COLOR</label><div className="swatches"><i/><i/><i/></div><label>SIZE</label><div className="sizes"><button>XS</button><button>S</button><button className="chosen">M</button><button>L</button><button>XL</button></div><button className="try-detail" onClick={tryIt}><Sparkles size={17}/> Try it on me</button><button className="bag">Add to bag <ShoppingBag size={16}/></button></div></div></div>}
