'use client';

import { useState } from 'react';
import { Bell, Camera, ChevronRight, Heart, ImagePlus, Menu, Search, ShoppingBag, Sparkles, User, X } from 'lucide-react';

type Product={id:number;name:string;category:string;price:number;image:string;reason:string;tag?:string};
const products:Product[]=[
{id:1,name:'Structured Overshirt',category:'Men · Fashion',price:3290,image:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=85',reason:'Matches your minimal style',tag:'AI PICK'},
{id:2,name:'Cloud Runner',category:'Running · Shoes',price:5490,image:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85',reason:'Because you like lightweight shoes'},
{id:3,name:'Noise Cancelling Headphones',category:'Audio · Tech',price:8990,image:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=85',reason:'Based on your tech history'},
{id:4,name:'Minimal Steel Watch',category:'Accessories',price:6990,image:'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=900&q=85',reason:'Fits your preferred colours'},
{id:5,name:'Everyday Knit Polo',category:'Men · Fashion',price:2490,image:'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=900&q=85',reason:'Popular with similar shoppers'},
{id:6,name:'Workspace Lamp',category:'Home · Living',price:3790,image:'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=85',reason:'You recently explored home upgrades'}
];
const interests=['Men’s Fashion','Sneakers','Technology','Home & Living','Fitness'];

export default function Home(){
 const [loggedIn,setLoggedIn]=useState(false); const [login,setLogin]=useState(false); const [upload,setUpload]=useState(false); const [liked,setLiked]=useState<number[]>([]); const [query,setQuery]=useState('');
 const toggleLike=(id:number)=>setLiked(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 const requestUpload=()=>loggedIn?setUpload(true):setLogin(true);
 const visible=products.filter(p=>`${p.name} ${p.category}`.toLowerCase().includes(query.toLowerCase()));
 return <main>
 <header className="topbar"><button className="menu"><Menu size={20}/></button><div className="brand"><span className="brand-mark"><Sparkles size={15}/></span>PERSONALIZED<span>ECOMMERCE</span></div><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your world"/></div><div className="actions"><button className="icon"><Bell size={18}/></button><button className="icon"><Heart size={18}/>{liked.length>0&&<i>{liked.length}</i>}</button><button className="icon"><ShoppingBag size={18}/></button><button className="avatar" onClick={()=>setLogin(true)}>{loggedIn?'S':<User size={17}/>}</button></div></header>
 <section className="welcome"><div><p className="eyebrow"><Sparkles size={13}/> YOUR PERSONAL SHOPPING SPACE</p><h1>{loggedIn?'Good afternoon, Shibin.':'Shopping, made personal.'}</h1><p>{loggedIn?"Your store is changing in real time based on what you like, explore and save.":'Explore freely. Sign in when you want us to start building a store around your taste.'}</p><div className="hero-actions"><button className="primary" onClick={()=>document.getElementById('foryou')?.scrollIntoView({behavior:'smooth'})}>Explore for you <ChevronRight size={16}/></button><button className="ghost" onClick={requestUpload}><Camera size={16}/> Try on with AI</button></div></div><div className="profile-card"><div className="profile-orb">✦</div><div><small>YOUR AI PROFILE</small><h3>{loggedIn?'Learning your taste':'Ready when you are'}</h3><p>{loggedIn?'Minimal · Modern · Tech · Fitness':'Sign in to save preferences and personalize every listing.'}</p></div><button onClick={()=>setLogin(true)}>{loggedIn?'View profile':'Personalize me'} <ChevronRight size={14}/></button></div></section>
 <section className="interest-strip"><div><span className="eyebrow">TUNED FOR YOU</span><h2>Your top interests</h2></div><div className="interest-list">{interests.map((x,i)=><button key={x} className={i===0?'interest active':'interest'}>{['◐','◒','◈','⌂','◉'][i]} {x}</button>)}</div></section>
 <section id="foryou" className="section"><div className="section-head"><div><p className="eyebrow"><Sparkles size={13}/> FOR YOU</p><h2>Picked for your taste.</h2><p>Not a generic catalog. These are ranked around your interests, browsing signals and preferences.</p></div><button className="view-all">View all <ChevronRight size={16}/></button></div><div className="product-grid">{visible.map(p=><article className="product" key={p.id}><div className="product-image"><img src={p.image} alt={p.name}/>{p.tag&&<span className="tag">{p.tag}</span>}<button className={liked.includes(p.id)?'heart liked':'heart'} onClick={()=>toggleLike(p.id)}><Heart size={17} fill={liked.includes(p.id)?'currentColor':'none'}/></button><button className="try-on" onClick={requestUpload}><Sparkles size={14}/> Try on</button></div><div className="product-meta"><div><span className="reason"><Sparkles size={11}/>{p.reason}</span><h3>{p.name}</h3><p>{p.category}</p></div><b>₹{p.price.toLocaleString('en-IN')}</b></div></article>)}</div></section>
 <section className="ai-banner"><div className="ai-icon"><ImagePlus size={26}/></div><div><p className="eyebrow">AI TRY-ON</p><h2>See products with you in the picture.</h2><p>Upload your photo and make your shopping profile even more personal.</p></div><button className="primary" onClick={requestUpload}>Upload your photo <ChevronRight size={16}/></button></section>
 <section className="section compact"><div className="section-head"><div><p className="eyebrow">DISCOVER</p><h2>New directions for you.</h2></div></div><div className="discover"><article><span>01</span><h3>Within your budget</h3><p>Products around the price range you usually explore.</p></article><article><span>02</span><h3>Because you liked</h3><p>More from styles, brands and categories you interact with.</p></article><article><span>03</span><h3>Try something new</h3><p>A little outside your usual pattern — still relevant to you.</p></article></div></section>
 {login&&<LoginModal onClose={()=>setLogin(false)} onLogin={()=>{setLoggedIn(true);setLogin(false);}}/>}
 {upload&&<UploadModal onClose={()=>setUpload(false)}/>}
 </main>
}

function LoginModal({onClose,onLogin}:{onClose:()=>void;onLogin:()=>void}){return <div className="backdrop" onMouseDown={onClose}><div className="login-modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={onClose}><X size={19}/></button><div className="login-symbol"><Sparkles size={24}/></div><p className="eyebrow">WELCOME IN</p><h2>Make this store yours.</h2><p>Sign in to save your interests, history, likes and AI shopping profile.</p><button className="google" onClick={onLogin}>G <span>Continue with Google</span></button><div className="divider"><span>or</span></div><input placeholder="Email address" type="email"/><button className="primary wide" onClick={onLogin}>Continue <ChevronRight size={16}/></button><small>Demo login for this UI prototype.</small></div></div>}
function UploadModal({onClose}:{onClose:()=>void}){return <div className="backdrop" onMouseDown={onClose}><div className="upload-modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={onClose}><X size={19}/></button><div className="upload-drop"><ImagePlus size={34}/><h2>Your virtual model</h2><p>Drop a clear full-body photo here to begin your AI try-on experience.</p><button className="primary">Choose photo <ChevronRight size={16}/></button><small>JPG or PNG · Your image stays connected to your profile</small></div></div></div>}
