'use client';
import {useState} from 'react';
import {ChevronRight,Heart,Sparkles,Bell,ShoppingBag,Search,X} from 'lucide-react';
type Product={id:number;name:string;category:string;price:number;image:string;reason:string;tag?:string};
const products:Product[]=[
{id:1,name:'Structured Overshirt',category:'Men’s Fashion',price:3290,image:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=85',reason:'Matches your minimal style',tag:'AI PICK'},
{id:2,name:'Everyday Knit Polo',category:'Men’s Fashion',price:2490,image:'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=900&q=85',reason:'Popular with similar shoppers'},
{id:3,name:'Tailored Linen Shirt',category:'Men’s Fashion',price:2890,image:'https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&w=900&q=85',reason:'Fits your clean everyday style'},
{id:4,name:'Silk Column Dress',category:'Women’s Fashion',price:8890,image:'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=900&q=85',reason:'Selected around your preferred silhouettes',tag:'AI PICK'},
{id:5,name:'Soft Tailored Blazer',category:'Women’s Fashion',price:7290,image:'https://images.unsplash.com/photo-1548624149-fb2d7b6b4c3d?auto=format&fit=crop&w=900&q=85',reason:'Matches your polished style'},
{id:6,name:'Everyday Midi Dress',category:'Women’s Fashion',price:4590,image:'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?auto=format&fit=crop&w=900&q=85',reason:'Based on your recent fashion signals'},
{id:7,name:'Relaxed Cotton Tee',category:'Casual Wear',price:1490,image:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80',reason:'An easy match for your everyday wardrobe'},
{id:8,name:'Relaxed Fit Denim',category:'Casual Wear',price:3490,image:'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=900&q=85',reason:'Pairs with pieces you already like'},
{id:9,name:'Lightweight Co-ord Set',category:'Casual Wear',price:5290,image:'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=85',reason:'Picked for your relaxed style'},
{id:10,name:'Classic Tailored Blazer',category:'Formal Wear',price:8490,image:'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=900&q=85',reason:'A strong match for your smart wardrobe'},
{id:11,name:'Pleated Formal Trousers',category:'Formal Wear',price:3990,image:'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=900&q=85',reason:'Complements your refined preferences'},
{id:12,name:'Performance Training Set',category:'Activewear',price:4290,image:'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=900&q=85',reason:'Selected for your active routine'},
{id:13,name:'Lightweight Run Jacket',category:'Activewear',price:5590,image:'https://images.unsplash.com/photo-1517964603305-11c0f6f66012?auto=format&fit=crop&w=900&q=85',reason:'Fits your movement and fitness interests'},
{id:14,name:'Studio Training Tee',category:'Activewear',price:2190,image:'https://images.unsplash.com/photo-1506629905607-d405d7d3c3cc?auto=format&fit=crop&w=900&q=85',reason:'A practical pick for your workouts'}
];
const filters=['All fashion','Men’s Fashion','Women’s Fashion','Casual Wear','Formal Wear','Activewear'];
export default function ProductsPage(){const [filter,setFilter]=useState('All fashion');const [tryProduct,setTryProduct]=useState<Product|null>(null);const [tryHistory,setTryHistory]=useState<Product[]>([]);const openTryOn=(p:Product)=>{setTryProduct(p);setTryHistory(h=>[p,...h.filter(x=>x.id!==p.id)].slice(0,5))};const list=products.filter(p=>filter==='All fashion'||p.category===filter);return <main><header className="topbar"><button className="menu" aria-label="Menu">☰</button><a className="brand" href="/"><span className="brand-mark"><Sparkles size={15}/></span>PERSONALIZED<span>ECOMMERCE</span></a><div className="search"><Search size={17}/><input placeholder="Search your world"/></div><div className="actions"><button className="icon"><Bell size={18}/></button><button className="icon"><Heart size={18}/></button><button className="icon"><ShoppingBag size={18}/></button><a className="login-link" href="/">LOGIN</a></div></header><section className="listing-page"><a className="detail-back" href="/">← Back to home</a><div className="listing-heading"><div><p className="eyebrow">PERSONALIZED COLLECTION</p><h1>More, picked for you.</h1><p>Explore clothing selected around your style, interests and shopping signals.</p></div><span>{list.length} pieces</span></div><div className="listing-filters">{filters.map(x=><button key={x} onClick={()=>setFilter(x)} className={filter===x?'active':''}>{x}</button>)}</div><div className="product-grid listing-grid">{list.map(p=><article className="product" key={p.id}><div className="product-image"><div className="product-open"><a className="product-image-link" href={'/products/'+p.id}><img src={p.image} alt={p.name}/></a><button className="image-try-on" onClick={()=>openTryOn(p)}><Sparkles size={14}/> Try on</button></div><button className="heart"><Heart size={17}/></button>{p.tag&&<span className="tag">{p.tag}</span>}</div><div className="product-meta"><div><p>{p.category}</p><h3>{p.name}</h3></div><strong>₹{p.price.toLocaleString('en-IN')}</strong></div><p className="reason"><Sparkles size={13}/>{p.reason}</p></article>)}</div></section>{tryProduct&&<TryOnStudio product={tryProduct} history={tryHistory} onSelect={setTryProduct} onClose={()=>setTryProduct(null)}/>}</main>}
function TryOnStudio({product,history,onSelect,onClose}:{product:Product;history:Product[];onSelect:(p:Product)=>void;onClose:()=>void}){return <div className="backdrop try-backdrop" onMouseDown={onClose}><div className="try-studio" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={onClose}><X size={19}/></button><div className="try-preview" style={{backgroundImage:`linear-gradient(90deg,rgba(19,20,24,.08),rgba(19,20,24,.2)),url(${product.image})`}}><div className="try-model"><div className="model-head"></div><div className="model-body"></div></div><span className="preview-label"><Sparkles size={13}/> Preview · {product.name}</span></div><div className="try-panel"><p className="eyebrow">TRY-ON STUDIO</p><h2>Your look, reimagined.</h2><div className="try-product"><img src={product.image} alt={product.name}/><div><h3>{product.name}</h3><p>{product.category} · ₹{product.price.toLocaleString('en-IN')}</p></div></div><div className="try-history-head"><span>Recently tried</span><b>{history.findIndex(x=>x.id===product.id)+1 || 1}/{history.length}</b></div><div className="try-history">{history.map(item=><button key={item.id} className={item.id===product.id?'active':''} onClick={()=>onSelect(item)}><img src={item.image} alt={item.name}/><span>{item.name}</span></button>)}</div><div className="try-actions"><button className="motion">See in motion <Sparkles size={14}/></button><button className="add-bag">Add to bag <ShoppingBag size={14}/></button></div><small>Try-on preview · Compare your recent looks before choosing.</small></div></div></div>}