'use client';

import { useEffect, useState } from 'react';
import { Bell, Camera, ChevronRight, Heart, ImagePlus, Menu, Search, ShoppingBag, Sparkles, User, X, ArrowUpRight, SlidersHorizontal } from 'lucide-react';

type Product={id:number;sku?:string;name:string;category:string;price:number;image:string;reason:string;tag?:string};
const products:Product[]=[
{id:1,sku:'SELENE-001',name:'Structured Overshirt',category:'Men’s Fashion',price:3290,image:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=85',reason:'Matches your minimal style',tag:'AI PICK'},
{id:2,sku:'SELENE-002',name:'Everyday Knit Polo',category:'Men’s Fashion',price:2490,image:'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=900&q=85',reason:'Popular with similar shoppers'},
{id:3,sku:'SELENE-003',name:'Tailored Linen Shirt',category:'Men’s Fashion',price:2890,image:'https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&w=900&q=85',reason:'Fits your clean everyday style'},
{id:4,sku:'SELENE-004',name:'Silk Column Dress',category:'Women’s Fashion',price:8890,image:'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=900&q=85',reason:'Selected around your preferred silhouettes',tag:'AI PICK'},
{id:5,sku:'SELENE-005',name:'Soft Tailored Blazer',category:'Women’s Fashion',price:7290,image:'https://images.unsplash.com/photo-1548624149-fb2d7b6b4c3d?auto=format&fit=crop&w=900&q=85',reason:'Matches your polished style'},
{id:6,sku:'SELENE-006',name:'Everyday Midi Dress',category:'Women’s Fashion',price:4590,image:'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?auto=format&fit=crop&w=900&q=85',reason:'Based on your recent fashion signals'},
{id:7,sku:'SELENE-007',name:'Relaxed Cotton Tee',category:'Casual Wear',price:1490,image:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80',reason:'An easy match for your everyday wardrobe'},
{id:8,sku:'SELENE-008',name:'Relaxed Fit Denim',category:'Casual Wear',price:3490,image:'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=900&q=85',reason:'Pairs with pieces you already like'},
{id:9,sku:'SELENE-009',name:'Lightweight Co-ord Set',category:'Casual Wear',price:5290,image:'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=85',reason:'Picked for your relaxed style'},
{id:10,sku:'SELENE-010',name:'Classic Tailored Blazer',category:'Formal Wear',price:8490,image:'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=900&q=85',reason:'A strong match for your smart wardrobe'},
{id:11,sku:'SELENE-011',name:'Pleated Formal Trousers',category:'Formal Wear',price:3990,image:'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=900&q=85',reason:'Complements your refined preferences'},
{id:12,sku:'SELENE-012',name:'Performance Training Set',category:'Activewear',price:4290,image:'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=900&q=85',reason:'Selected for your active routine'},
{id:13,sku:'SELENE-013',name:'Lightweight Run Jacket',category:'Activewear',price:5590,image:'https://images.unsplash.com/photo-1517964603305-11c0f6f66012?auto=format&fit=crop&w=900&q=85',reason:'Fits your movement and fitness interests'},
{id:14,sku:'SELENE-014',name:'Studio Training Tee',category:'Activewear',price:2190,image:'https://images.unsplash.com/photo-1506629905607-d405d7d3c3cc?auto=format&fit=crop&w=900&q=85',reason:'A practical pick for your workouts'}
];
const interests=['Men’s Fashion','Women’s Fashion','Casual Wear','Formal Wear','Activewear'];
const collections=[
['Minimal wardrobe','Pieces that work with what you already like','https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=900&q=85'],
['Better everyday tech','Useful upgrades, selected around your interests','https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=85'],
['Move more','Running and fitness picks for your routine','https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=900&q=85']
];

export default function Home(){
 const [loggedIn,setLoggedIn]=useState(false),[login,setLogin]=useState(false),[upload,setUpload]=useState(false),[liked,setLiked]=useState<number[]>([]),[query,setQuery]=useState(''),[activeInterest,setActiveInterest]=useState('Men’s Fashion'),[uploadedPhoto,setUploadedPhoto]=useState<string|null>(null),[selectedProduct,setSelectedProduct]=useState<Product|null>(null),[listingOpen,setListingOpen]=useState(false),[tryProduct,setTryProduct]=useState<Product|null>(null),[tryHistory,setTryHistory]=useState<Product[]>([]);
 const toggleLike=(id:number)=>setLiked(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 const requestUpload=()=>loggedIn?setUpload(true):setLogin(true);
 const openHeroTryOn=()=>{const product=products.find(p=>p.category.includes('Fashion'))||products[0];setTryProduct(product);setTryHistory(h=>[product,...h.filter(x=>x.id!==product.id)].slice(0,6));};
 useEffect(()=>{if(selectedProduct||listingOpen)window.scrollTo({top:0,behavior:'smooth'});},[selectedProduct,listingOpen]);
 const openTryOn=(product:Product)=>{setTryProduct(product);setTryHistory(h=>[product,...h.filter(x=>x.id!==product.id)].slice(0,6));};
 const interestMatch:Record<string,string>={'Men’s Fashion':'Men’s Fashion','Women’s Fashion':'Women’s Fashion','Casual Wear':'Casual Wear','Formal Wear':'Formal Wear',Activewear:'Activewear'};
 const visible=products.filter(p=>p.category.includes(interestMatch[activeInterest])&&`${p.name} ${p.category}`.toLowerCase().includes(query.toLowerCase()));
 return <main className={selectedProduct?'detail-open':''}>
 <header className="topbar"><button className="menu"><Menu size={20}/></button><div className="brand"><span className="brand-mark"><Sparkles size={15}/></span>PERSONALIZED<span>ECOMMERCE</span></div><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your world"/></div><div className="actions"><button className="icon"><Bell size={18}/></button><button className="icon"><Heart size={18}/>{liked.length>0&&<i>{liked.length}</i>}</button><button className="icon"><ShoppingBag size={18}/></button>{loggedIn?<button className="avatar" onClick={()=>setLogin(true)}>S</button>:<button className="login-link" onClick={()=>setLogin(true)}>LOGIN</button>}</div></header>{listingOpen&&<ProductListing products={products} activeInterest={activeInterest} onBack={()=>setListingOpen(false)} onSelect={p=>{setListingOpen(false);setSelectedProduct(p)}} onTry={openTryOn}/>} {selectedProduct&&<ProductDetail product={selectedProduct} liked={liked.includes(selectedProduct.id)} onBack={()=>setSelectedProduct(null)} onLike={()=>toggleLike(selectedProduct.id)} onTry={()=>openTryOn(selectedProduct)}/>} 
 <section className="welcome"><div><p className="eyebrow"><Sparkles size={13}/> YOUR PERSONAL SHOPPING SPACE</p><h1><span className="hero-greeting">Hey John,</span><span className="hero-shopping">SHOPPING</span><span className="hero-personal"><span>made</span><span className="hero-personal-accent">personal.</span></span></h1><p>{loggedIn?"Your store is changing in real time based on what you like, explore and save.":'Explore freely. Sign in when you want us to start building a store around your taste.'}</p><div className="hero-actions"><button className="primary" onClick={()=>document.getElementById('foryou')?.scrollIntoView({behavior:'smooth'})}>Explore for you <ChevronRight size={16}/></button><button className="ghost" data-tryon-product="SELENE-001"><Camera size={16}/> Try on with AI</button></div></div><div className="profile-card"><div className="profile-copy"><div className="profile-orb">✦</div><div><small>YOUR AI PROFILE</small><h3>{loggedIn?'Learning your taste':'Ready when you are'}</h3><p>{loggedIn?'Minimal · Modern · Tech · Fitness':'Sign in to save preferences and personalize every listing.'}</p></div><button onClick={()=>setLogin(true)}>{loggedIn?'View profile':'Personalize me'} <ChevronRight size={14}/></button></div><div className="profile-shopping-art" aria-hidden="true"><div className="art-spark one">✦</div><div className="art-spark two">✦</div><div className="art-bag"></div><div className="art-clothes"></div><div className="art-sunglasses">◒</div></div></div></section>
 <section className="interest-strip"><div><span className="eyebrow">TUNED FOR YOU</span><h2>Your top interests</h2></div><div className="interest-list">{interests.map((x,i)=><button key={x} onClick={()=>{setActiveInterest(x);requestAnimationFrame(()=>document.getElementById('foryou')?.scrollIntoView({behavior:'smooth',block:'start'}));}} className={activeInterest===x?'interest active':'interest'}>{['◐','◒','◈','◌','◉'][i]} {x}</button>)}</div></section>
 <section id="foryou" className="section"><div className="section-head"><div><p className="eyebrow"><Sparkles size={13}/> FOR YOU</p><h2>Picked for your taste.</h2><p>Not a generic catalog. These are ranked around your interests, browsing signals and preferences.</p></div><button className="view-all" onClick={()=>window.location.href="/products"}>View all <ChevronRight size={16}/></button></div><div className="product-grid">{visible.map(p=><article className="product" key={p.id}><div className="product-image"><div className="product-open"><button className="product-image-link" aria-label={`View ${p.name}`} onClick={()=>window.location.href=`/products/${p.id}`}><img src={p.image} alt={p.name}/></button><button className="image-try-on" data-tryon-product={p.sku || 'SELENE-001'}><Sparkles size={14}/> Try on</button></div>{p.tag&&<span className="tag">{p.tag}</span>}<button className={liked.includes(p.id)?'heart liked':'heart'} onClick={()=>toggleLike(p.id)}><Heart size={17} fill={liked.includes(p.id)?'currentColor':'none'}/></button></div><div className="product-meta"><div><span className="reason"><Sparkles size={11}/>{p.reason}</span><h3>{p.name}</h3><p>{p.category}</p></div><b>₹{p.price.toLocaleString('en-IN')}</b></div></article>)}</div></section>
 <section className="taste-section"><div className="taste-copy"><p className="eyebrow"><SlidersHorizontal size={13}/> YOUR TASTE PROFILE</p><h2>Your store is learning what <em>feels like you.</em></h2><p>Every view, save and search helps us rank products more intelligently. You stay in control of what shapes your recommendations.</p><div className="signals"><span>Style <b>Minimal</b></span><span>Budget <b>₹2k–₹10k</b></span><span>Colours <b>Dark & neutral</b></span></div><button className="ghost">Manage profile <ArrowUpRight size={15}/></button></div><div className="taste-score"><small>PERSONALIZATION</small><strong>84<span>%</span></strong><p>We have a strong read on your current interests.</p><div className="score-bar"><i/></div><small className="score-note">Updated from your latest activity</small></div></section>
 <section className="collections section"><div className="section-head"><div><p className="eyebrow">PERSONALIZED COLLECTIONS</p><h2>Made from your interests.</h2></div></div><div className="collection-grid">{collections.map(([title,text,img],i)=><article className={'collection c'+i} key={title}><img src={img} alt=""/><div><span>0{i+1}</span><h3>{title}</h3><p>{text}</p><button>Explore <ArrowUpRight size={15}/></button></div></article>)}</div></section>
 <section className="ai-banner"><div className="ai-icon"><ImagePlus size={26}/></div><div><p className="eyebrow">AI TRY-ON</p><h2>See products with you in the picture.</h2><p>Upload your photo and make your shopping profile even more personal.</p></div><button className="primary" onClick={()=>(window as any).TryOn?.openPanel()}>Upload your photo <ChevronRight size={16}/></button></section>
 <section className="activity-section"><div className="section-head"><div><p className="eyebrow">CONTINUE EXPLORING</p><h2>Your recent signals.</h2><p>A quick look at the things helping shape your next recommendations.</p></div></div><div className="activity-grid"><article><b>12</b><span>Products viewed</span><p>More minimalist fashion than anything else this week.</p></article><article><b>{liked.length || 3}</b><span>Items saved</span><p>Saved items are getting more weight in your next product ranking.</p></article><article><b>04</b><span>Categories explored</span><p>Fashion, tech and fitness are your strongest current interests.</p></article><article className="explore-card"><Sparkles size={21}/><h3>Open the feed</h3><p>See everything the AI has selected for you.</p><button>Explore <ArrowUpRight size={15}/></button></article></div></section>
 <section className="section compact"><div className="section-head"><div><p className="eyebrow">DISCOVER</p><h2>New directions for you.</h2></div></div><div className="discover"><article><span>01</span><h3>Within your budget</h3><p>Products around the price range you usually explore.</p></article><article><span>02</span><h3>Because you liked</h3><p>More from styles, brands and categories you interact with.</p></article><article><span>03</span><h3>Try something new</h3><p>A little outside your usual pattern — still relevant to you.</p></article></div></section>
 <footer><div className="footer-top"><div className="footer-brand"><div className="brand"><span className="brand-mark"><Sparkles size={15}/></span>PERSONALIZED</div><h2>A store that gets better at knowing you.</h2><p>Discover products around your interests, not just the products everyone else sees.</p><div className="footer-search"><input placeholder="Get occasional product updates"/><button><ArrowUpRight size={17}/></button></div></div><div className="footer-links"><div><h4>DISCOVER</h4><a>For you</a><a>Collections</a><a>Categories</a><a>AI Try-On</a></div><div><h4>ACCOUNT</h4><a>My profile</a><a>Saved items</a><a>Orders</a><a>Preferences</a></div><div><h4>HELP</h4><a>How it works</a><a>Privacy</a><a>Contact</a><a>Feedback</a></div></div></div><div className="footer-bottom"><span>© 2026 Personalized Ecommerce</span><span>Built around your taste, always in your control.</span><div><a>Instagram</a><a>LinkedIn</a></div></div></footer>
 {login&&<LoginModal onClose={()=>setLogin(false)} onLogin={()=>{setLoggedIn(true);setLogin(false);}}/>}</main>
}
function LoginModal({onClose,onLogin}:{onClose:()=>void;onLogin:()=>void}){return <div className="backdrop" onMouseDown={onClose}><div className="login-modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={onClose}><X size={19}/></button><div className="login-symbol"><Sparkles size={24}/></div><p className="eyebrow">WELCOME IN</p><h2>Make this store yours.</h2><p>Sign in to save your interests, history, likes and AI shopping profile.</p><button className="google" onClick={onLogin}>G <span>Continue with Google</span></button><div className="divider"><span>or</span></div><input placeholder="Email address" type="email"/><button className="primary wide" onClick={onLogin}>Continue <ChevronRight size={16}/></button><small>Demo login for this UI prototype.</small></div></div>}
function UploadModal({onClose,onUpload}:{onClose:()=>void;onUpload:(photo:string)=>void}){const handlePhoto=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>onUpload(String(reader.result));reader.readAsDataURL(file)};return <div className="backdrop" onMouseDown={onClose}><div className="upload-modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={onClose}><X size={19}/></button><div className="upload-drop"><ImagePlus size={34}/><h2>Your virtual model</h2><p>Drop a clear full-body photo here to begin your AI try-on experience.</p><label className="primary upload-choice">Choose photo <ChevronRight size={16}/><input type="file" accept="image/*" onChange={e=>handlePhoto(e.target.files?.[0])}/></label><small>JPG or PNG · Your image stays connected to your profile</small></div></div></div>}
function TryOnStudio({product,history,photo,onSelect,onClose}:{product:Product;history:Product[];photo:string|null;onSelect:(p:Product)=>void;onClose:()=>void}){return <div className="backdrop try-backdrop" onMouseDown={onClose}><div className="try-studio" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={onClose}><X size={19}/></button><div className="try-preview" style={{backgroundImage:`linear-gradient(90deg,rgba(19,20,24,.08),rgba(19,20,24,.2)),url(${photo||product.image})`}}><div className="try-model"><div className="model-head"></div><div className="model-body"></div></div><span className="preview-label"><Sparkles size={13}/> Preview · {product.name}</span></div><div className="try-panel"><p className="eyebrow">TRY-ON STUDIO</p><h2>Your look, reimagined.</h2><div className="try-product"><img src={product.image} alt={product.name}/><div><h3>{product.name}</h3><p>{product.category} · ₹{product.price.toLocaleString('en-IN')}</p></div></div><div className="try-history-head"><span>Recently tried</span><b>{history.findIndex(x=>x.id===product.id)+1 || 1}/{history.length}</b></div><div className="try-history">{history.map(item=><button key={item.id} className={item.id===product.id?'active':''} onClick={()=>onSelect(item)}><img src={item.image} alt={item.name}/><span>{item.name}</span></button>)}</div><div className="try-actions"><button className="motion">See in motion <Sparkles size={14}/></button><button className="add-bag">Add to bag <ShoppingBag size={14}/></button></div><small>Try-on preview · Compare your recent looks before choosing.</small></div></div></div>}
function ProductDetail({product,liked,onBack,onLike,onTry}:{product:Product;liked:boolean;onBack:()=>void;onLike:()=>void;onTry:()=>void}){return <section className="product-detail"><button className="detail-back" onClick={onBack}>← Back to recommendations</button><div className="detail-layout"><div className="detail-gallery"><img src={product.image} alt={product.name}/><span className="detail-ai"><Sparkles size={13}/> AI selected for you</span></div><div className="detail-info"><p className="eyebrow">{product.category.toUpperCase()}</p><h1>{product.name}</h1><p className="detail-reason"><Sparkles size={14}/>{product.reason}</p><h2>₹{product.price.toLocaleString('en-IN')}</h2><p className="detail-copy">Selected around your personal shopping signals and style preferences. Explore the product, save it for later, or see how it could look in your Try-On Studio.</p><div className="detail-options"><span>SELECT SIZE</span><div><button>S</button><button className="active">M</button><button>L</button><button>XL</button></div></div><div className="detail-actions"><button className="detail-try" data-tryon-product={product.sku || 'SELENE-001'}><Sparkles size={16}/> Try on with AI</button><button className={liked?'detail-like liked':'detail-like'} onClick={onLike}><Heart size={18} fill={liked?'currentColor':'none'}/></button></div><button className="detail-bag">Add to bag <ShoppingBag size={16}/></button></div></div></section>}
function ProductListing({products,activeInterest,onBack,onSelect,onTry}:{products:Product[];activeInterest:string;onBack:()=>void;onSelect:(p:Product)=>void;onTry:(p:Product)=>void}){const [filter,setFilter]=useState(activeInterest);const list=products.filter(p=>filter==='All fashion'||p.category===filter);return <section className="listing-page"><button className="detail-back" onClick={onBack}>← Back to home</button><div className="listing-heading"><div><p className="eyebrow">PERSONALIZED COLLECTION</p><h1>More, picked for you.</h1><p>Explore clothing selected around your style, interests and shopping signals.</p></div><span>{list.length} pieces</span></div><div className="listing-filters">{['All fashion','Men’s Fashion','Women’s Fashion','Casual Wear','Formal Wear','Activewear'].map(x=><button key={x} onClick={()=>setFilter(x)} className={filter===x?'active':''}>{x}</button>)}</div><div className="product-grid listing-grid">{list.map(p=><article className="product" key={p.id}><div className="product-image"><button className="product-open" onClick={()=>onSelect(p)}><img src={p.image} alt={p.name}/></button><button className="heart"><Heart size={17}/></button>{p.tag&&<span className="tag">{p.tag}</span>}</div><div className="product-meta"><div><p>{p.category}</p><h3>{p.name}</h3></div><strong>₹{p.price.toLocaleString('en-IN')}</strong></div><p className="reason"><Sparkles size={13}/>{p.reason}</p><button className="try-on" data-tryon-product={p.sku || 'SELENE-001'}><Sparkles size={14}/> Try on</button></article>)}</div></section>}